#!/usr/bin/env python3


import rospy
from std_msgs.msg import Int64


def get_user_input():
    while True:
        res = input("Send next message? (Y/n): ")
        if len(res) == 0 or res == 'Y' or res == 'y':
            return True
        elif res == 'n' or res == 'N':
            return False


def main():
    rospy.init_node('int_publisher')
    pub = rospy.Publisher('topic', Int64, queue_size=2)

    print(f'publishing Int64 messages on topic {pub.resolved_name}')
    msg = Int64()
    while not rospy.is_shutdown() and get_user_input():
        pub.publish(msg)
        msg.data += 1


if __name__ == '__main__':
    try:
        main()
    except rospy.ROSInteruptException:
        pass
