#!/usr/bin/env fish

# update
#
# a script used to update the or_protocol running on one of the nodes in the
# mesh network testbed remotely

if test -z "$OR_PROTOCOL_DIR"
    echo "OR_PROTOCOL_DIR not set, exiting."
    exit
end

cd $OR_PROTOCOL_DIR

if not test -d .catkin_tools
    if test -d /opt/ros/melodic
        catkin config --init --extend /opt/ros/melodic
    else if test -d /opt/ros/noetic
        catkin config --init --extend /opt/ros/noetic
    else
        echo "no ROS installation found under /opt/ros"
        exit
    end
end

catkin clean -y
catkin build or_protocol
# catkin run_tests