task_agent_ids: [44, 46]
mid_agent_ids: [42]
max_range: 30.0  # max communication range in meters
sync_topics:
  - /scarab44/goals: {type: exploration_msgs/Goal, reliable: true, queue_size: 4, source: 44}
  - /scarab46/goals: {type: exploration_msgs/Goal, reliable: true, queue_size: 4, source: 46}
  - /scarab44/frontiers: {type: exploration_msgs/FrontierGoals, reliable: true, queue_size: 4, source: 44}
  - /scarab46/frontiers: {type: exploration_msgs/FrontierGoals, reliable: true, queue_size: 4, source: 46}
  - /command: {type: experiment_msgs/Command, reliable: true, queue_size: 4, source: 46, all: true}
