task_agent_ids: [41, 42, 46]
mid_agent_ids: []
max_range: 30.0  # max communication range in meters
sync_topics:
  - /scarab41/goals: {type: exploration_msgs/Goal, reliable: false, queue_size: 4, source: 41}
  - /scarab41/frontiers: {type: exploration_msgs/FrontierGoals, reliable: false, queue_size: 4, source: 41}
  - /scarab42/goals: {type: exploration_msgs/Goal, reliable: false, queue_size: 4, source: 42}
  - /scarab42/frontiers: {type: exploration_msgs/FrontierGoals, reliable: false, queue_size: 4, source: 42}
  - /scarab46/goals: {type: exploration_msgs/Goal, reliable: false, queue_size: 4, source: 46}
  - /scarab46/frontiers: {type: exploration_msgs/FrontierGoals, reliable: false, queue_size: 4, source: 46}
